# .github/workflows/cicd.yml

name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Only secret you need is the service account JSON
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      # Build the Docker image, tagging it with your hardcoded path
      - name: Build Docker image
        run: |
          docker build -t \
            europe-west2-docker.pkg.dev/aiops-bone-zone/tiny-llm-app/tiny-llm-app:latest \
            -f docker/Dockerfile .

      # Push that same image
      - name: Push Docker image
        run: |
          docker push \
            europe-west2-docker.pkg.dev/aiops-bone-zone/tiny-llm-app/tiny-llm-app:latest

      # Terraform Init & Apply (no -var references)
      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Wait 10 minutes for ephemeral demo
        run: sleep 600

      # Terraform Destroy (again, no -var references)
      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve
