# .github/workflows/cicd.yml

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      # 1) Build with the SAME full path you plan to push:
      - name: Build Docker image
        run: |
          docker build -t \
            europe-west2-docker.pkg.dev/aiops-bone-zone/tiny-llm-app/tiny-llm-app:latest \
            -f docker/Dockerfile .

      # 2) Push that exact same name:
      - name: Push Docker image
        run: |
          docker push \
            europe-west2-docker.pkg.dev/aiops-bone-zone/tiny-llm-app/tiny-llm-app:latest

      # 3) Use that same image in Terraform:
      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "image=europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tiny-llm-app/tiny-llm-app:latest"

      - name: Wait 10 minutes for ephemeral demo
        run: sleep 600

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "image=europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tiny-llm-app/tiny-llm-app:latest"
